/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AvailableSlot = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'time' : IDL.Text,
  'isBooked' : IDL.Bool,
});
export const Result_3 = IDL.Variant({ 'ok' : AvailableSlot, 'err' : IDL.Text });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'dob' : IDL.Text,
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'tob' : IDL.Text,
  'service' : IDL.Text,
  'status' : IDL.Text,
  'question' : IDL.Text,
  'clientName' : IDL.Text,
  'createdAt' : IDL.Int,
  'birthPlace' : IDL.Text,
  'email' : IDL.Text,
  'slotId' : IDL.Nat,
  'slotDate' : IDL.Text,
  'gender' : IDL.Text,
  'slotTime' : IDL.Text,
});
export const Result_2 = IDL.Variant({ 'ok' : Booking, 'err' : IDL.Text });
export const Result = IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text });
export const Result_1 = IDL.Variant({
  'ok' : IDL.Vec(Booking),
  'err' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addSlot' : IDL.Func([IDL.Text, IDL.Text], [Result_3], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookAppointment' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
        IDL.Text,
      ],
      [Result_2],
      [],
    ),
  'cancelBooking' : IDL.Func([IDL.Nat], [Result], []),
  'getAvailableSlots' : IDL.Func([], [IDL.Vec(AvailableSlot)], ['query']),
  'getBookings' : IDL.Func([], [Result_1], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeSlot' : IDL.Func([IDL.Nat], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AvailableSlot = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'time' : IDL.Text,
    'isBooked' : IDL.Bool,
  });
  const Result_3 = IDL.Variant({ 'ok' : AvailableSlot, 'err' : IDL.Text });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'dob' : IDL.Text,
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'tob' : IDL.Text,
    'service' : IDL.Text,
    'status' : IDL.Text,
    'question' : IDL.Text,
    'clientName' : IDL.Text,
    'createdAt' : IDL.Int,
    'birthPlace' : IDL.Text,
    'email' : IDL.Text,
    'slotId' : IDL.Nat,
    'slotDate' : IDL.Text,
    'gender' : IDL.Text,
    'slotTime' : IDL.Text,
  });
  const Result_2 = IDL.Variant({ 'ok' : Booking, 'err' : IDL.Text });
  const Result = IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text });
  const Result_1 = IDL.Variant({ 'ok' : IDL.Vec(Booking), 'err' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addSlot' : IDL.Func([IDL.Text, IDL.Text], [Result_3], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookAppointment' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
          IDL.Text,
        ],
        [Result_2],
        [],
      ),
    'cancelBooking' : IDL.Func([IDL.Nat], [Result], []),
    'getAvailableSlots' : IDL.Func([], [IDL.Vec(AvailableSlot)], ['query']),
    'getBookings' : IDL.Func([], [Result_1], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeSlot' : IDL.Func([IDL.Nat], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };