/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Remedy = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'bookingId' : IDL.Nat,
  'clientName' : IDL.Text,
  'createdAt' : IDL.Int,
});
export const Result_1 = IDL.Variant({ 'ok' : Remedy, 'err' : IDL.Text });
export const AvailableSlot = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'time' : IDL.Text,
  'isBooked' : IDL.Bool,
});
export const Result_12 = IDL.Variant({
  'ok' : AvailableSlot,
  'err' : IDL.Text,
});
export const Result_11 = IDL.Variant({
  'ok' : IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat)),
  'err' : IDL.Text,
});
export const Referral = IDL.Record({
  'owner' : IDL.Principal,
  'code' : IDL.Text,
  'createdAt' : IDL.Int,
  'timesUsed' : IDL.Nat,
  'coinsEarned' : IDL.Nat,
});
export const Result_10 = IDL.Variant({
  'ok' : IDL.Vec(Referral),
  'err' : IDL.Text,
});
export const Result_8 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'dob' : IDL.Text,
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'tob' : IDL.Text,
  'service' : IDL.Text,
  'status' : IDL.Text,
  'couponUsed' : IDL.Text,
  'question' : IDL.Text,
  'clientName' : IDL.Text,
  'createdAt' : IDL.Int,
  'birthPlace' : IDL.Text,
  'email' : IDL.Text,
  'slotId' : IDL.Nat,
  'feeApplied' : IDL.Nat,
  'slotDate' : IDL.Text,
  'gender' : IDL.Text,
  'slotTime' : IDL.Text,
});
export const Result_9 = IDL.Variant({ 'ok' : Booking, 'err' : IDL.Text });
export const Result_2 = IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text });
export const Coupon = IDL.Record({
  'active' : IDL.Bool,
  'code' : IDL.Text,
  'usageCount' : IDL.Nat,
  'maxUsage' : IDL.Nat,
  'discountPercent' : IDL.Nat,
});
export const Result = IDL.Variant({ 'ok' : Coupon, 'err' : IDL.Text });
export const Result_6 = IDL.Variant({
  'ok' : IDL.Vec(Remedy),
  'err' : IDL.Text,
});
export const Result_7 = IDL.Variant({
  'ok' : IDL.Vec(Booking),
  'err' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ServiceFee = IDL.Record({
  'serviceName' : IDL.Text,
  'currency' : IDL.Text,
  'amount' : IDL.Nat,
});
export const Result_5 = IDL.Variant({
  'ok' : IDL.Vec(Coupon),
  'err' : IDL.Text,
});
export const Result_4 = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
export const Result_3 = IDL.Variant({ 'ok' : ServiceFee, 'err' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addRemedy' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [Result_1],
      [],
    ),
  'addSlot' : IDL.Func([IDL.Text, IDL.Text], [Result_12], []),
  'adminGetAllCoinBalances' : IDL.Func([], [Result_11], ['query']),
  'adminGetAllReferrals' : IDL.Func([], [Result_10], ['query']),
  'applyReferralCode' : IDL.Func([IDL.Text], [Result_8], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookAppointment' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
      ],
      [Result_9],
      [],
    ),
  'cancelBooking' : IDL.Func([IDL.Nat], [Result_2], []),
  'claimFirstAdmin' : IDL.Func([], [IDL.Bool], []),
  'createCoupon' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [Result], []),
  'deleteCoupon' : IDL.Func([IDL.Text], [Result_2], []),
  'deleteRemedy' : IDL.Func([IDL.Nat], [Result_2], []),
  'forceClaimAdmin' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'generateReferralCode' : IDL.Func([], [Result_8], []),
  'getAllRemedies' : IDL.Func([], [Result_6], ['query']),
  'getAvailableSlots' : IDL.Func([], [IDL.Vec(AvailableSlot)], ['query']),
  'getBookings' : IDL.Func([], [Result_7], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCoinBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getReferralCode' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getRemediesForBooking' : IDL.Func([IDL.Nat], [Result_6], ['query']),
  'getServiceFees' : IDL.Func([], [IDL.Vec(ServiceFee)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listCoupons' : IDL.Func([], [Result_5], ['query']),
  'redeemCoins' : IDL.Func([IDL.Principal, IDL.Nat], [Result_4], []),
  'removeServiceFee' : IDL.Func([IDL.Text], [Result_2], []),
  'removeSlot' : IDL.Func([IDL.Nat], [Result_2], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setServiceFee' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [Result_3], []),
  'toggleCouponStatus' : IDL.Func([IDL.Text, IDL.Bool], [Result_2], []),
  'updateRemedy' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [Result_1], []),
  'validateCoupon' : IDL.Func([IDL.Text], [Result], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Remedy = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'bookingId' : IDL.Nat,
    'clientName' : IDL.Text,
    'createdAt' : IDL.Int,
  });
  const Result_1 = IDL.Variant({ 'ok' : Remedy, 'err' : IDL.Text });
  const AvailableSlot = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'time' : IDL.Text,
    'isBooked' : IDL.Bool,
  });
  const Result_12 = IDL.Variant({ 'ok' : AvailableSlot, 'err' : IDL.Text });
  const Result_11 = IDL.Variant({
    'ok' : IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat)),
    'err' : IDL.Text,
  });
  const Referral = IDL.Record({
    'owner' : IDL.Principal,
    'code' : IDL.Text,
    'createdAt' : IDL.Int,
    'timesUsed' : IDL.Nat,
    'coinsEarned' : IDL.Nat,
  });
  const Result_10 = IDL.Variant({ 'ok' : IDL.Vec(Referral), 'err' : IDL.Text });
  const Result_8 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'dob' : IDL.Text,
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'tob' : IDL.Text,
    'service' : IDL.Text,
    'status' : IDL.Text,
    'couponUsed' : IDL.Text,
    'question' : IDL.Text,
    'clientName' : IDL.Text,
    'createdAt' : IDL.Int,
    'birthPlace' : IDL.Text,
    'email' : IDL.Text,
    'slotId' : IDL.Nat,
    'feeApplied' : IDL.Nat,
    'slotDate' : IDL.Text,
    'gender' : IDL.Text,
    'slotTime' : IDL.Text,
  });
  const Result_9 = IDL.Variant({ 'ok' : Booking, 'err' : IDL.Text });
  const Result_2 = IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text });
  const Coupon = IDL.Record({
    'active' : IDL.Bool,
    'code' : IDL.Text,
    'usageCount' : IDL.Nat,
    'maxUsage' : IDL.Nat,
    'discountPercent' : IDL.Nat,
  });
  const Result = IDL.Variant({ 'ok' : Coupon, 'err' : IDL.Text });
  const Result_6 = IDL.Variant({ 'ok' : IDL.Vec(Remedy), 'err' : IDL.Text });
  const Result_7 = IDL.Variant({ 'ok' : IDL.Vec(Booking), 'err' : IDL.Text });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ServiceFee = IDL.Record({
    'serviceName' : IDL.Text,
    'currency' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const Result_5 = IDL.Variant({ 'ok' : IDL.Vec(Coupon), 'err' : IDL.Text });
  const Result_4 = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
  const Result_3 = IDL.Variant({ 'ok' : ServiceFee, 'err' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addRemedy' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [Result_1],
        [],
      ),
    'addSlot' : IDL.Func([IDL.Text, IDL.Text], [Result_12], []),
    'adminGetAllCoinBalances' : IDL.Func([], [Result_11], ['query']),
    'adminGetAllReferrals' : IDL.Func([], [Result_10], ['query']),
    'applyReferralCode' : IDL.Func([IDL.Text], [Result_8], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookAppointment' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [Result_9],
        [],
      ),
    'cancelBooking' : IDL.Func([IDL.Nat], [Result_2], []),
    'claimFirstAdmin' : IDL.Func([], [IDL.Bool], []),
    'createCoupon' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [Result], []),
    'deleteCoupon' : IDL.Func([IDL.Text], [Result_2], []),
    'deleteRemedy' : IDL.Func([IDL.Nat], [Result_2], []),
    'forceClaimAdmin' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'generateReferralCode' : IDL.Func([], [Result_8], []),
    'getAllRemedies' : IDL.Func([], [Result_6], ['query']),
    'getAvailableSlots' : IDL.Func([], [IDL.Vec(AvailableSlot)], ['query']),
    'getBookings' : IDL.Func([], [Result_7], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCoinBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getReferralCode' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getRemediesForBooking' : IDL.Func([IDL.Nat], [Result_6], ['query']),
    'getServiceFees' : IDL.Func([], [IDL.Vec(ServiceFee)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listCoupons' : IDL.Func([], [Result_5], ['query']),
    'redeemCoins' : IDL.Func([IDL.Principal, IDL.Nat], [Result_4], []),
    'removeServiceFee' : IDL.Func([IDL.Text], [Result_2], []),
    'removeSlot' : IDL.Func([IDL.Nat], [Result_2], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setServiceFee' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [Result_3], []),
    'toggleCouponStatus' : IDL.Func([IDL.Text, IDL.Bool], [Result_2], []),
    'updateRemedy' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [Result_1], []),
    'validateCoupon' : IDL.Func([IDL.Text], [Result], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };