/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AvailableSlot {
  'id' : bigint,
  'date' : string,
  'time' : string,
  'isBooked' : boolean,
}
export interface Booking {
  'id' : bigint,
  'dob' : string,
  'lat' : number,
  'lng' : number,
  'tob' : string,
  'service' : string,
  'status' : string,
  'couponUsed' : string,
  'question' : string,
  'clientName' : string,
  'createdAt' : bigint,
  'birthPlace' : string,
  'email' : string,
  'slotId' : bigint,
  'feeApplied' : bigint,
  'slotDate' : string,
  'gender' : string,
  'slotTime' : string,
}
export interface Coupon {
  'active' : boolean,
  'code' : string,
  'usageCount' : bigint,
  'maxUsage' : bigint,
  'discountPercent' : bigint,
}
export interface Referral {
  'owner' : Principal,
  'code' : string,
  'createdAt' : bigint,
  'timesUsed' : bigint,
  'coinsEarned' : bigint,
}
export interface Remedy {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'bookingId' : bigint,
  'clientName' : string,
  'createdAt' : bigint,
}
export type Result = { 'ok' : Coupon } |
  { 'err' : string };
export type Result_1 = { 'ok' : Remedy } |
  { 'err' : string };
export type Result_10 = { 'ok' : Booking } |
  { 'err' : string };
export type Result_11 = { 'ok' : Array<Referral> } |
  { 'err' : string };
export type Result_12 = { 'ok' : Array<[Principal, bigint]> } |
  { 'err' : string };
export type Result_13 = { 'ok' : AvailableSlot } |
  { 'err' : string };
export type Result_2 = { 'ok' : boolean } |
  { 'err' : string };
export type Result_3 = { 'ok' : ServiceFee } |
  { 'err' : string };
export type Result_4 = { 'ok' : bigint } |
  { 'err' : string };
export type Result_5 = { 'ok' : Array<Coupon> } |
  { 'err' : string };
export type Result_6 = { 'ok' : Array<Remedy> } |
  { 'err' : string };
export type Result_7 = { 'ok' : Array<Booking> } |
  { 'err' : string };
export type Result_8 = { 'ok' : Array<AvailableSlot> } |
  { 'err' : string };
export type Result_9 = { 'ok' : string } |
  { 'err' : string };
export interface ServiceFee {
  'serviceName' : string,
  'currency' : string,
  'amount' : bigint,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addRemedy' : ActorMethod<[bigint, string, string, string], Result_1>,
  'addSlot' : ActorMethod<[string, string], Result_13>,
  'adminGetAllCoinBalances' : ActorMethod<[], Result_12>,
  'adminGetAllReferrals' : ActorMethod<[], Result_11>,
  'applyReferralCode' : ActorMethod<[string], Result_9>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bookAppointment' : ActorMethod<
    [
      string,
      string,
      string,
      bigint,
      string,
      string,
      string,
      number,
      number,
      string,
      string,
      [] | [string],
    ],
    Result_10
  >,
  'cancelBooking' : ActorMethod<[bigint], Result_2>,
  'claimFirstAdmin' : ActorMethod<[], boolean>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createCoupon' : ActorMethod<[string, bigint, bigint], Result>,
  'deleteBooking' : ActorMethod<[bigint], Result_2>,
  'deleteCoupon' : ActorMethod<[string], Result_2>,
  'deleteRemedy' : ActorMethod<[bigint], Result_2>,
  'forceClaimAdmin' : ActorMethod<[string], boolean>,
  'generateReferralCode' : ActorMethod<[], Result_9>,
  'getAllRemedies' : ActorMethod<[], Result_6>,
  'getAllSlots' : ActorMethod<[], Result_8>,
  'getAvailableSlots' : ActorMethod<[], Array<AvailableSlot>>,
  'getBookings' : ActorMethod<[], Result_7>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCoinBalance' : ActorMethod<[], bigint>,
  'getReferralCode' : ActorMethod<[], [] | [string]>,
  'getRemediesForBooking' : ActorMethod<[bigint], Result_6>,
  'getServiceFees' : ActorMethod<[], Array<ServiceFee>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listCoupons' : ActorMethod<[], Result_5>,
  'redeemCoins' : ActorMethod<[Principal, bigint], Result_4>,
  'removeServiceFee' : ActorMethod<[string], Result_2>,
  'removeSlot' : ActorMethod<[bigint], Result_2>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setServiceFee' : ActorMethod<[string, bigint, string], Result_3>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'toggleCouponStatus' : ActorMethod<[string, boolean], Result_2>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateRemedy' : ActorMethod<[bigint, string, string], Result_1>,
  'validateCoupon' : ActorMethod<[string], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];