/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AvailableSlot {
  'id' : bigint,
  'date' : string,
  'time' : string,
  'isBooked' : boolean,
}
export interface Booking {
  'id' : bigint,
  'dob' : string,
  'lat' : number,
  'lng' : number,
  'tob' : string,
  'service' : string,
  'status' : string,
  'question' : string,
  'clientName' : string,
  'createdAt' : bigint,
  'birthPlace' : string,
  'email' : string,
  'slotId' : bigint,
  'slotDate' : string,
  'gender' : string,
  'slotTime' : string,
}
export type Result = { 'ok' : boolean } |
  { 'err' : string };
export type Result_1 = { 'ok' : Array<Booking> } |
  { 'err' : string };
export type Result_2 = { 'ok' : Booking } |
  { 'err' : string };
export type Result_3 = { 'ok' : AvailableSlot } |
  { 'err' : string };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addSlot' : ActorMethod<[string, string], Result_3>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bookAppointment' : ActorMethod<
    [
      string,
      string,
      string,
      bigint,
      string,
      string,
      string,
      number,
      number,
      string,
      string,
    ],
    Result_2
  >,
  'cancelBooking' : ActorMethod<[bigint], Result>,
  'getAvailableSlots' : ActorMethod<[], Array<AvailableSlot>>,
  'getBookings' : ActorMethod<[], Result_1>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'isAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeSlot' : ActorMethod<[bigint], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];