/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Result_2 = {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: string;
};
export interface AvailableSlot {
    id: bigint;
    date: string;
    time: string;
    isBooked: boolean;
}
export type Result_6 = {
    __kind__: "ok";
    ok: Array<Remedy>;
} | {
    __kind__: "err";
    err: string;
};
export interface Coupon {
    active: boolean;
    code: string;
    usageCount: bigint;
    maxUsage: bigint;
    discountPercent: bigint;
}
export type Result_5 = {
    __kind__: "ok";
    ok: Array<Coupon>;
} | {
    __kind__: "err";
    err: string;
};
export type Result_9 = {
    __kind__: "ok";
    ok: Booking;
} | {
    __kind__: "err";
    err: string;
};
export type Result_12 = {
    __kind__: "ok";
    ok: AvailableSlot;
} | {
    __kind__: "err";
    err: string;
};
export interface ServiceFee {
    serviceName: string;
    currency: string;
    amount: bigint;
}
export type Result_1 = {
    __kind__: "ok";
    ok: Remedy;
} | {
    __kind__: "err";
    err: string;
};
export type Result_4 = {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
};
export type Result_11 = {
    __kind__: "ok";
    ok: Array<[Principal, bigint]>;
} | {
    __kind__: "err";
    err: string;
};
export interface Remedy {
    id: bigint;
    title: string;
    content: string;
    bookingId: bigint;
    clientName: string;
    createdAt: bigint;
}
export type Result = {
    __kind__: "ok";
    ok: Coupon;
} | {
    __kind__: "err";
    err: string;
};
export type Result_3 = {
    __kind__: "ok";
    ok: ServiceFee;
} | {
    __kind__: "err";
    err: string;
};
export type Result_10 = {
    __kind__: "ok";
    ok: Array<Referral>;
} | {
    __kind__: "err";
    err: string;
};
export type Result_8 = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export interface Referral {
    owner: Principal;
    code: string;
    createdAt: bigint;
    timesUsed: bigint;
    coinsEarned: bigint;
}
export type Result_7 = {
    __kind__: "ok";
    ok: Array<Booking>;
} | {
    __kind__: "err";
    err: string;
};
export interface Booking {
    id: bigint;
    dob: string;
    lat: number;
    lng: number;
    tob: string;
    service: string;
    status: string;
    couponUsed: string;
    question: string;
    clientName: string;
    createdAt: bigint;
    birthPlace: string;
    email: string;
    slotId: bigint;
    feeApplied: bigint;
    slotDate: string;
    gender: string;
    slotTime: string;
}
export interface UserProfile {
    name: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addRemedy(bookingId: bigint, clientName: string, title: string, content: string): Promise<Result_1>;
    addSlot(date: string, time: string): Promise<Result_12>;
    adminGetAllCoinBalances(): Promise<Result_11>;
    adminGetAllReferrals(): Promise<Result_10>;
    applyReferralCode(code: string): Promise<Result_8>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bookAppointment(clientName: string, email: string, service: string, slotId: bigint, dob: string, tob: string, birthPlace: string, lat: number, lng: number, gender: string, question: string, couponCode: string | null): Promise<Result_9>;
    cancelBooking(id: bigint): Promise<Result_2>;
    claimFirstAdmin(): Promise<boolean>;
    createCoupon(code: string, discountPercent: bigint, maxUsage: bigint): Promise<Result>;
    deleteCoupon(code: string): Promise<Result_2>;
    deleteRemedy(id: bigint): Promise<Result_2>;
    forceClaimAdmin(userSecret: string): Promise<boolean>;
    generateReferralCode(): Promise<Result_8>;
    getAllRemedies(): Promise<Result_6>;
    getAvailableSlots(): Promise<Array<AvailableSlot>>;
    getBookings(): Promise<Result_7>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCoinBalance(): Promise<bigint>;
    getReferralCode(): Promise<string | null>;
    getRemediesForBooking(bookingId: bigint): Promise<Result_6>;
    getServiceFees(): Promise<Array<ServiceFee>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isAdmin(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    listCoupons(): Promise<Result_5>;
    redeemCoins(userPrincipal: Principal, amount: bigint): Promise<Result_4>;
    removeServiceFee(serviceName: string): Promise<Result_2>;
    removeSlot(id: bigint): Promise<Result_2>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setServiceFee(serviceName: string, amount: bigint, currency: string): Promise<Result_3>;
    toggleCouponStatus(code: string, isActive: boolean): Promise<Result_2>;
    updateRemedy(id: bigint, title: string, content: string): Promise<Result_1>;
    validateCoupon(code: string): Promise<Result>;
}
import type { AvailableSlot as _AvailableSlot, Booking as _Booking, Coupon as _Coupon, Referral as _Referral, Remedy as _Remedy, Result as _Result, Result_1 as _Result_1, Result_10 as _Result_10, Result_11 as _Result_11, Result_12 as _Result_12, Result_2 as _Result_2, Result_3 as _Result_3, Result_4 as _Result_4, Result_5 as _Result_5, Result_6 as _Result_6, Result_7 as _Result_7, Result_8 as _Result_8, Result_9 as _Result_9, ServiceFee as _ServiceFee, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addRemedy(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.addRemedy(arg0, arg1, arg2, arg3);
                return from_candid_Result_1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRemedy(arg0, arg1, arg2, arg3);
            return from_candid_Result_1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async addSlot(arg0: string, arg1: string): Promise<Result_12> {
        if (this.processError) {
            try {
                const result = await this.actor.addSlot(arg0, arg1);
                return from_candid_Result_12_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSlot(arg0, arg1);
            return from_candid_Result_12_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetAllCoinBalances(): Promise<Result_11> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllCoinBalances();
                return from_candid_Result_11_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllCoinBalances();
            return from_candid_Result_11_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetAllReferrals(): Promise<Result_10> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllReferrals();
                return from_candid_Result_10_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllReferrals();
            return from_candid_Result_10_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async applyReferralCode(arg0: string): Promise<Result_8> {
        if (this.processError) {
            try {
                const result = await this.actor.applyReferralCode(arg0);
                return from_candid_Result_8_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyReferralCode(arg0);
            return from_candid_Result_8_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bookAppointment(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: string, arg5: string, arg6: string, arg7: number, arg8: number, arg9: string, arg10: string, arg11: string | null): Promise<Result_9> {
        if (this.processError) {
            try {
                const result = await this.actor.bookAppointment(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, to_candid_opt_n13(this._uploadFile, this._downloadFile, arg11));
                return from_candid_Result_9_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookAppointment(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, to_candid_opt_n13(this._uploadFile, this._downloadFile, arg11));
            return from_candid_Result_9_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async cancelBooking(arg0: bigint): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelBooking(arg0);
                return from_candid_Result_2_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelBooking(arg0);
            return from_candid_Result_2_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async claimFirstAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.claimFirstAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimFirstAdmin();
            return result;
        }
    }
    async createCoupon(arg0: string, arg1: bigint, arg2: bigint): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.createCoupon(arg0, arg1, arg2);
                return from_candid_Result_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCoupon(arg0, arg1, arg2);
            return from_candid_Result_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteCoupon(arg0: string): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCoupon(arg0);
                return from_candid_Result_2_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCoupon(arg0);
            return from_candid_Result_2_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteRemedy(arg0: bigint): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRemedy(arg0);
                return from_candid_Result_2_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRemedy(arg0);
            return from_candid_Result_2_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async forceClaimAdmin(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.forceClaimAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.forceClaimAdmin(arg0);
            return result;
        }
    }
    async generateReferralCode(): Promise<Result_8> {
        if (this.processError) {
            try {
                const result = await this.actor.generateReferralCode();
                return from_candid_Result_8_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateReferralCode();
            return from_candid_Result_8_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRemedies(): Promise<Result_6> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRemedies();
                return from_candid_Result_6_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRemedies();
            return from_candid_Result_6_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableSlots(): Promise<Array<AvailableSlot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableSlots();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableSlots();
            return result;
        }
    }
    async getBookings(): Promise<Result_7> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookings();
                return from_candid_Result_7_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookings();
            return from_candid_Result_7_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCoinBalance(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoinBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoinBalance();
            return result;
        }
    }
    async getReferralCode(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReferralCode();
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReferralCode();
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRemediesForBooking(arg0: bigint): Promise<Result_6> {
        if (this.processError) {
            try {
                const result = await this.actor.getRemediesForBooking(arg0);
                return from_candid_Result_6_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRemediesForBooking(arg0);
            return from_candid_Result_6_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getServiceFees(): Promise<Array<ServiceFee>> {
        if (this.processError) {
            try {
                const result = await this.actor.getServiceFees();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServiceFees();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async isAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listCoupons(): Promise<Result_5> {
        if (this.processError) {
            try {
                const result = await this.actor.listCoupons();
                return from_candid_Result_5_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCoupons();
            return from_candid_Result_5_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async redeemCoins(arg0: Principal, arg1: bigint): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.redeemCoins(arg0, arg1);
                return from_candid_Result_4_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.redeemCoins(arg0, arg1);
            return from_candid_Result_4_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeServiceFee(arg0: string): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.removeServiceFee(arg0);
                return from_candid_Result_2_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeServiceFee(arg0);
            return from_candid_Result_2_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeSlot(arg0: bigint): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.removeSlot(arg0);
                return from_candid_Result_2_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeSlot(arg0);
            return from_candid_Result_2_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setServiceFee(arg0: string, arg1: bigint, arg2: string): Promise<Result_3> {
        if (this.processError) {
            try {
                const result = await this.actor.setServiceFee(arg0, arg1, arg2);
                return from_candid_Result_3_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setServiceFee(arg0, arg1, arg2);
            return from_candid_Result_3_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async toggleCouponStatus(arg0: string, arg1: boolean): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleCouponStatus(arg0, arg1);
                return from_candid_Result_2_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleCouponStatus(arg0, arg1);
            return from_candid_Result_2_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateRemedy(arg0: bigint, arg1: string, arg2: string): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRemedy(arg0, arg1, arg2);
                return from_candid_Result_1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRemedy(arg0, arg1, arg2);
            return from_candid_Result_1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async validateCoupon(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.validateCoupon(arg0);
                return from_candid_Result_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateCoupon(arg0);
            return from_candid_Result_n18(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Result_10_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_10): Result_10 {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Result_11_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_11): Result_11 {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Result_12_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_12): Result_12 {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result_2_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_2): Result_2 {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Result_3_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_3): Result_3 {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_Result_4_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_4): Result_4 {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Result_5_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_5): Result_5 {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Result_6_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_6): Result_6 {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Result_7_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_7): Result_7 {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Result_8_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_8): Result_8 {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Result_9_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_9): Result_9 {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Booking;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Booking;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: boolean;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Coupon;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Coupon;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Remedy;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Remedy;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_Remedy>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<Remedy>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_Booking>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<Booking>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_Coupon>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<Coupon>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _ServiceFee;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: ServiceFee;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _AvailableSlot;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: AvailableSlot;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<[Principal, bigint]>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<[Principal, bigint]>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_Referral>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<Referral>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function to_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
